### ISSUE TITLE
USB not supported

### ISSUE THREAD

**Issue by intellisec** [yukimizake/ThermalDotNet#3]
Hi,
tried to use it with usb pos printer.... does not work, due to the fact, that usb is not serial....
Is there any kind of work around?

**Comment by yukimizake** [comment]
Hi,
If you're on Windows be sure the "virtual" COM port of your printer is shown in the device manager.
Then, use the right port number in your code like this : 
SerialPort printerPort = new SerialPort("COM1", 9600);

**Comment by fookeong** [comment]
Hi Sir,
"virtual" COM port it is needed third party software??

**Comment by intellisec** [comment]
https://download.epson-biz.com/modules/pos/index.php?page=soft&pcat=3&scat=36
That's the virtual COM-Driver for Epson-printers.
Works fine.
Be sure to assign USB-Printer to COM-port and then in Code:

`SerialPort printerPort = new SerialPort("COM1", 9600);
printerPort.Open();
ThermalPrinter printer = new ThermalPrinter(printerPort);
printer.WriteLine("test");
printerPort.Close();`

Worked fine for me.
